import { RegistroPatron } from './ProgramaCalibracionScreen'; // Ajusta la ruta si es necesario

// Datos extraídos de AA AG-CAL-F13-00...F13Prog.CalibyMtto.csv
// Filtrado por "Calibración" para ajustarse a la lógica de la pantalla.
export const patronesData: RegistroPatron[] = [
  {
    noControl: 'AG-001',
    descripcion: 'Bloques Patrón 33 piezas',
    serie: '980495',
    marca: 'MITUTOYO',
    modelo: 'S/M',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-10-18',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-002',
    descripcion: 'Bloques Patrón 10 pzs',
    serie: '506361',
    marca: 'MITUTOYO',
    modelo: '516-926-26',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-26',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-003',
    descripcion: 'Calibrador de procesos',
    serie: '9188082',
    marca: 'FLUKE',
    modelo: '743B',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-15',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-004',
    descripcion: 'Regla Semiflexible',
    serie: '1906',
    marca: 'MITUTOYO',
    modelo: '182-309',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-03-12',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-005',
    descripcion: 'Shunt',
    serie: 'S/N',
    marca: 'N/A',
    modelo: 'S/M',
    frecuencia: '15 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-006',
    descripcion: 'Block Patrón 200 mm',
    serie: '40145',
    marca: 'MITUTOYO',
    modelo: '200 mm',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-10-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-007',
    descripcion: 'Block Patrón 300 mm',
    serie: '30335',
    marca: 'MITUTOYO',
    modelo: '300 mm',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-10-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-008',
    descripcion: 'Digital Pressure Gage 10000 psi',
    serie: '9941257',
    marca: 'OMEGA',
    modelo: 'DPG-4000-10K',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-12-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-009',
    descripcion: 'Megabox Resistance',
    serie: 'S/N',
    marca: 'S/M',
    modelo: 'S/M',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-07',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-010',
    descripcion: 'Micrómetro de Exteriores Digital',
    serie: '35117081',
    marca: 'MITUTOYO',
    modelo: '293-721-30',
    frecuencia: '18 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-03-07',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-012',
    descripcion: 'Retícula Graduada',
    serie: 'RET - 01',
    marca: 'Peak',
    modelo: 'S/M',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-21',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-013',
    descripcion: 'Transductor de Par Torsional 338.9 Nm',
    serie: 'BMX-04-09-039',
    marca: 'MOUNTZ',
    modelo: 'BMX-250F',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-06-10',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-014',
    descripcion: 'Transductor Estático de Par Torsional 33.9 Nm',
    serie: '1000014',
    marca: 'STURTEVANT RICHMONT',
    modelo: 'STT3001-P',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-015',
    descripcion: 'Angle Blocks',
    serie: '202675',
    marca: 'ANYTIME TOOLS',
    modelo: '1-30 DEGREES',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-03-26',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-016',
    descripcion: '5 1/2 Digital Multimeter',
    serie: '8000180',
    marca: 'KEITHLEY',
    modelo: '21110',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-09-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-017',
    descripcion: 'Masa 2 kg',
    serie: 'B00025',
    marca: 'Provimex Cientifica',
    modelo: 'PVE-2KM1',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-29',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-018',
    descripcion: 'Masa 5 kg',
    serie: 'B00212',
    marca: 'Provimex Cientifica',
    modelo: 'PVE-5KM1',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-29',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-019',
    descripcion: 'Masa 10 kg',
    serie: 'B00141',
    marca: 'Provimex Cientifica',
    modelo: 'PVE-10KM1',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-29',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-020',
    descripcion: 'Masa 20 kg (10 piezas)',
    serie: 'B01786 a B01795',
    marca: 'Provimex Cientifica',
    modelo: 'PVE-20KM1',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-29',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  // Nota: AG-020 tiene dos entradas de "Calibración", se usará la segunda.
  {
    noControl: 'AG-020',
    descripcion: 'Masa 20 kg (15 piezas)',
    serie: 'B02953 a B02967',
    marca: 'Provimex Cientifica',
    modelo: 'PVE-20KM1',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-021',
    descripcion: 'Transductor Estático de Par Torsional 203.4 Nm',
    serie: '718746',
    marca: 'STURTEVANT RICHMONT',
    modelo: 'TT150',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-25',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-022',
    descripcion: 'Masa 500 g',
    serie: 'S/N',
    marca: 'Provimex Cientifica',
    modelo: 'S/M',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-02-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-023',
    descripcion: 'Masa 1000 g',
    serie: 'S/N',
    marca: 'Provimex Cientifica',
    modelo: 'S/M',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-02-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-024',
    descripcion: 'Punta de Alta Tensión',
    serie: '49630019',
    marca: 'FLUKE',
    modelo: '80K-6',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-11',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-025',
    descripcion: 'Transductor Estático de Par Torsional 11 Nm',
    serie: '14275',
    marca: 'IHOSS',
    modelo: 'HP-100',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-08',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-026',
    descripcion: 'Crónometro',
    serie: 'CRAG-01',
    marca: 'STOP WATCH',
    modelo: 'PS-100',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-07-26',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AGS-001',
    descripcion: 'Calibrador Digital',
    serie: 'A19241454',
    marca: 'MITUTOYO',
    modelo: '500-196-30',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-03-07',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'ID04555',
    descripcion: 'Calibrador Multifunción',
    serie: 'V01856J21',
    marca: 'Transmille',
    modelo: '1000',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-10-07',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-028',
    descripcion: 'Punta de Alta Tensión 40 kV',
    serie: '39760006',
    marca: 'FLUKE',
    modelo: '80K-40',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-11',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-029',
    descripcion: 'Block Patrón 75 mm',
    serie: '151019',
    marca: 'mitutoyo',
    modelo: 'S/M',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-030',
    descripcion: 'Block Patrón 100 mm',
    serie: '163379',
    marca: 'mitutoyo',
    modelo: 'S/M',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-031',
    descripcion: 'Patrón de rugosidad',
    serie: '361232105',
    marca: 'mitutoyo',
    modelo: '178-602',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-30',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-032',
    descripcion: 'Surface Plate repeat checking calibrator',
    serie: '2561',
    marca: 'Metrology',
    modelo: 'PLA-9003',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-12',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-033',
    descripcion: 'Escala de Vidrio 200 mm',
    serie: '140011',
    marca: 'Metrology',
    modelo: 'OP-SS8',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-01-12',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-034',
    descripcion: 'Transductor de presión PV 350',
    serie: 'AGPV-001',
    marca: 'Fluke',
    modelo: 'PV 350',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2026-01-07',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-035',
    descripcion: 'Juego de Lainas Plásticas',
    serie: 'S/N',
    marca: 'DeFelsko',
    modelo: 'S/M',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-09',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-036',
    descripcion: 'Juego de Pernos Patron Lisos',
    serie: 'AGP-001',
    marca: 'Fowler',
    modelo: '52-485-048-0',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-12-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-037',
    descripcion: 'Transductor Estático de Par Torsional 1345 Nm',
    serie: '713351',
    marca: 'STURTEVANT RICHMONT',
    modelo: 'TT1000',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-26',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-039',
    descripcion: 'Juego de pesas F2',
    serie: 'S/N',
    marca: 'S/M',
    modelo: 'S/M',
    frecuencia: '18 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2024-12-18',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-040',
    descripcion: 'Celda de Carga',
    serie: 'VD01A',
    marca: 'Monad',
    modelo: '30 T',
    frecuencia: '18 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-06-08',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-041',
    descripcion: 'Juego de Bloques Patron 8 pzas.',
    serie: '210053',
    marca: 'Shars',
    modelo: '303-5330',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-11-22',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-042',
    descripcion: 'Solucción pH 4',
    serie: 'CC781397',
    marca: 'OAKTON',
    modelo: 'pH 4',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-07-06',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-043',
    descripcion: 'Solucción pH 7',
    serie: 'CC783229',
    marca: 'OAKTON',
    modelo: 'pH 7',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-08-02',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-044',
    descripcion: 'Solucción pH 10',
    serie: 'CC780480',
    marca: 'OAKTON',
    modelo: 'pH 10',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-06-27',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-045',
    descripcion: 'Soluccion de conductividad 99.70 μS/cm',
    serie: 'Lote: CC25314',
    marca: 'Traceable',
    modelo: '99.70 μS/cm',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-01-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-046',
    descripcion: 'Soluccion de conductividad 1414 μS/cm',
    serie: 'Lote: CC25453',
    marca: 'Traceable',
    modelo: '1414 μS/cm',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-02-06',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-047',
    descripcion: 'Soluccion de conductividad 10,018 μS/cm',
    serie: 'Lote: CC25299',
    marca: 'Traceable',
    modelo: '10,018 μS/cm',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-01-19',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-048',
    descripcion: 'Soluccion de viscosidad C60',
    serie: 'C60',
    marca: 'Cannon',
    modelo: 'C60',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: 'Por Comprar',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-049',
    descripcion: 'Soluccion de viscosidad C200',
    serie: 'C200',
    marca: 'Cannon',
    modelo: 'C200',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: 'Por Comprar',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-051',
    descripcion: 'Transductor Estático de Par Torsional 5.65 Nm',
    serie: '1000264',
    marca: 'STURTEVANT RICHMONT',
    modelo: 'STP501-P',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-23',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-052',
    descripcion: 'Manómetro Digital 1000 psi',
    serie: '5335895',
    marca: 'Druck',
    modelo: 'DPI104',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-11-28',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-053',
    descripcion: 'Transmisor de flujo de gas',
    serie: '69875',
    marca: 'Omega',
    modelo: 'FMA-2609A',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-27',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-054',
    descripcion: 'Sound Calibrator',
    serie: '2300140',
    marca: 'AZ Instrument Corp.',
    modelo: '8930',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-10',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-055',
    descripcion: 'Multimetro',
    serie: '45440303',
    marca: 'Fluke',
    modelo: '175',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-11',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-056',
    descripcion: 'Acelerometro Uniaxial',
    serie: 'LW036212 & 165807',
    marca: 'PCB Piezotronics',
    modelo: '480C02 & J353B33',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2024-12-20',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-057',
    descripcion: 'Decade Inductance Box',
    serie: '20230421EIN',
    marca: 'Tilak',
    modelo: 'S/M',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-09-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-058',
    descripcion: 'Capacitance Decade Box',
    serie: '1615666',
    marca: 'GME',
    modelo: 'CD-300',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-26',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-059',
    descripcion: 'Bloques Patron 81 pzas Grado 0',
    serie: '210043',
    marca: 'Shars',
    modelo: '303-5307C',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-04-03',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-060',
    descripcion: 'Black Body',
    serie: '21101163',
    marca: 'Omega',
    modelo: 'BB703',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-061',
    descripcion: 'Higrómetro Digital',
    serie: '51141365',
    marca: 'Fluke',
    modelo: '971',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-22',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-062',
    descripcion: 'Termometro Infrarrojo',
    serie: '35320343WS',
    marca: 'Fluke',
    modelo: '561',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2025-05-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AG-063',
    descripcion: 'Transductor Estático de Par Torsional 50 Lbf*ft',
    serie: 'LTT2012103',
    marca: 'MOUNTZ',
    modelo: 'LTT-2100',
    frecuencia: '12 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
  {
    noControl: 'AGS-06',
    descripcion: 'Mini Digital Protractor',
    serie: 'EQDIM01',
    marca: 'Fowler',
    modelo: 'Mini MAG (54-422-450-1)',
    frecuencia: '24 Meses ± 5 Dias',
    tipoServicio: 'Calibración',
    fecha: '2027-01-24',
    prioridad: 'Media',
    ubicacion: 'Laboratorio',
    responsable: 'Jesús Sustaita',
    estadoProceso: 'operativo',
    historial: [],
  },
];